version: "3.8"

x-web-environment: &web-environment
  HTTP_PORT: 3000
  DB_POOL_SIZE: 40
  CLUSTER_WORKERS: 5
  POSTGRES_HOST: postgres
  POSTGRES_USER: local_user
  POSTGRES_PASSWORD: local_password

x-web-template: &web-template
  depends_on:
    - postgres
  expose:
    - "3000"
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    <<: *web-environment
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "0.6GB"

services:
  web1:
    <<: *web-template
    hostname: web1

  web2:
    <<: *web-template
    hostname: web2

  postgres:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rinha-backend-nestjs-2023-q3
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "1.5GB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "0.3GB"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
